variavel = input("DIgite algo:")
print("Tipo primitivo : ",type(variavel))
print("Só espaços?",variavel.isspace())
print("Numero?",variavel.isnumeric())
print("Alfabetic?",variavel.isalpha())
print("alfanumeric?",variavel.isalnum())
print("MAIUSCULAS?",variavel.isupper())
print("minusculas??",variavel.islower())
print("Capitalizado?",variavel.istitle())
